name: mapbox-studio-classic
version: master
summary: Application for vector tile driven map design.
description: |
  Mapbox Studio Classic is a standalone map design application that uses
  vector tiles. Mapbox Studio Classic gives you instant streaming access to
  massive global tilesets like Mapbox Streets, Mapbox Terrain, and Mapbox
  Satellite without importing any data onto your computer.

grade: stable
confinement: strict

apps:
  server:
    command: sh -c \"cd $SNAP/lib/node_modules/mapbox-studio && npm start\"
    plugs: [network]

parts:
  mapbox-studio-classic:
    source: .
    plugin: nodejs
    build-packages: [curl, git]
